change to with-x=no

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -5,8 +5,22 @@ export ZOPEN_TYPE="GIT"
 
 export ZOPEN_GIT_URL="https://github.com/vim/vim.git"
 export ZOPEN_GIT_DEPS="git make zoslib ncurses"
-export ZOPEN_EXTRA_CONFIGURE_OPTS="--with-features=big --without-x --enable-gui=no"
-export ZOPEN_CHECK="skip"
+export ZOPEN_GIT_TAG="v9.0.0846"
+export ZOPEN_EXTRA_CONFIGURE_OPTS="--with-features=big --with-x=no --enable-gui=no"
+export ZOPEN_CHECK="./src/vim"
+export ZOPEN_CHECK_OPTS="--version"
+
+zopen_check_results()
+{
+  dir="$1"
+  pfx="$2"
+  chk="$1/$2_check.log"
+  grep -q "VIM - Vi IMproved 9.0" $chk
+  failures=$?
+  echo "actualFailures:$failures"
+  echo "totalTests:1"
+  echo "expectedFailures:0"
+}
 
 zopen_append_to_env() {
 cat <<EOF
